export const TOP_HEADLINE_REQUEST = "TOP_HEADLINE_REQUEST";
export const TOP_HEADLINE_SUCCESS = "TOP_HEADLINE_SUCCESS";
export const TOP_HEADLINE_FAIL = "TOP_HEADLINE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
